In [2]:
import pandas as pd

In [3]:
iphone_df = pd.read_csv('data/iphone.csv', index_col=0)

In [4]:
iphone_df

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [5]:
iphone_df.loc['iPhone X']

출시일        2017-11-03
디스플레이             5.8
메모리               3GB
출시 버전        iOS 11.1
Face ID           Yes
Name: iPhone X, dtype: object

In [6]:
iphone_df.loc[['iPhone X', 'iPhone 8']]

                 출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X  2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone 8  2017-09-22    4.7  2GB  iOS 11.0      No

In [7]:
type(iphone_df.loc[['iPhone X', 'iPhone 8']])

pandas.core.frame.DataFrame

In [8]:
iphone_df['Face ID']

iPhone 7          No
iPhone 7 Plus     No
iPhone 8          No
iPhone 8 Plus     No
iPhone X         Yes
iPhone XS        Yes
iPhone XS Max    Yes
Name: Face ID, dtype: object

In [9]:
iphone_df[['Face ID', '출시일', '메모리']]

              Face ID         출시일  메모리
iPhone 7           No  2016-09-16  2GB
iPhone 7 Plus      No  2016-09-16  3GB
iPhone 8           No  2017-09-22  2GB
iPhone 8 Plus      No  2017-09-22  3GB
iPhone X          Yes  2017-11-03  3GB
iPhone XS         Yes  2018-09-21  4GB
iPhone XS Max     Yes  2018-09-21  4GB

In [10]:
iphone_df.loc[:'iPhone XS']

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes

In [11]:
iphone_df.loc[:, '메모리':'Face ID']

               메모리     출시 버전 Face ID
iPhone 7       2GB  iOS 10.0      No
iPhone 7 Plus  3GB  iOS 10.0      No
iPhone 8       2GB  iOS 11.0      No
iPhone 8 Plus  3GB  iOS 11.0      No
iPhone X       3GB  iOS 11.1     Yes
iPhone XS      4GB  iOS 12.0     Yes
iPhone XS Max  4GB  iOS 12.0     Yes

In [12]:
iphone_df.loc[:'iPhone 8', '메모리':'Face ID']

               메모리     출시 버전 Face ID
iPhone 7       2GB  iOS 10.0      No
iPhone 7 Plus  3GB  iOS 10.0      No
iPhone 8       2GB  iOS 11.0      No

In [13]:
iphone_df.loc[[True, False, True, True, False, True, False]]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes

In [14]:
iphone_df.loc[[True, False, True, True, False, True, False]]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes

In [15]:
iphone_df['디스플레이'] > 5

iPhone 7         False
iPhone 7 Plus     True
iPhone 8         False
iPhone 8 Plus     True
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: 디스플레이, dtype: bool

In [16]:
iphone_df.loc[iphone_df['디스플레이']> 5]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [17]:
result = (iphone_df['디스플레이'] > 5) & (iphone_df['Face ID'] == 'Yes')

In [18]:
result

iPhone 7         False
iPhone 7 Plus    False
iPhone 8         False
iPhone 8 Plus    False
iPhone X          True
iPhone XS         True
iPhone XS Max     True
dtype: bool

In [19]:
iphone_df.loc[result]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [20]:
iphone_df[result]

                      출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [21]:
iphone_df.iloc[2, 4]

'No'

In [22]:
iphone_df.iloc[[1, 3], [1, 4]]

               디스플레이 Face ID
iPhone 7 Plus    5.5      No
iPhone 8 Plus    5.5      No

In [23]:
iphone_df.iloc[3:, 1:4]

               디스플레이  메모리     출시 버전
iPhone 8 Plus    5.5  3GB  iOS 11.0
iPhone X         5.8  3GB  iOS 11.1
iPhone XS        5.8  4GB  iOS 12.0
iPhone XS Max    6.5  4GB  iOS 12.0

In [24]:
iphone_df.loc['iPhone 8', '메모리'] = '2.5GB'

In [25]:
iphone_df

                      출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5    3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2.5GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB  iOS 12.0     Yes

In [26]:
iphone_df.loc['iPhone 8', '출시 버전'] = 'iOS 10.3'

In [27]:
iphone_df

                      출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5    3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2.5GB  iOS 10.3      No
iPhone 8 Plus  2017-09-22    5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB  iOS 12.0     Yes

In [28]:
iphone_df.loc['iPhone 8']

출시일        2017-09-22
디스플레이             4.7
메모리             2.5GB
출시 버전        iOS 10.3
Face ID            No
Name: iPhone 8, dtype: object

In [29]:
iphone_df.loc['iPhone 8'] = ['2016-09-22', '4.7', '2GB', 'iOS 11.0', 'No']

In [30]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16   5.5  3GB  iOS 10.0      No
iPhone 8       2016-09-22   4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22   5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     Yes

In [31]:
iphone_df['디스플레이']

iPhone 7         4.7
iPhone 7 Plus    5.5
iPhone 8         4.7
iPhone 8 Plus    5.5
iPhone X         5.8
iPhone XS        5.8
iPhone XS Max    6.5
Name: 디스플레이, dtype: object

In [32]:
iphone_df['Face ID'] = 'No'

In [33]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16   5.5  3GB  iOS 10.0      No
iPhone 8       2016-09-22   4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22   5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03   5.8  3GB  iOS 11.1      No
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0      No
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0      No

In [34]:
iphone_df['Face ID'] = 'Yes'

In [35]:
iphone_df

                      출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0     Yes
iPhone 7 Plus  2016-09-16   5.5  3GB  iOS 10.0     Yes
iPhone 8       2016-09-22   4.7  2GB  iOS 11.0     Yes
iPhone 8 Plus  2017-09-22   5.5  3GB  iOS 11.0     Yes
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     Yes

In [36]:
iphone_df[['디스플레이', 'Face ID']]

              디스플레이 Face ID
iPhone 7        4.7     Yes
iPhone 7 Plus   5.5     Yes
iPhone 8        4.7     Yes
iPhone 8 Plus   5.5     Yes
iPhone X        5.8     Yes
iPhone XS       5.8     Yes
iPhone XS Max   6.5     Yes